### ISSUE TITLE
MyTasks 2 tabs not working

### ISSUE THREAD

**Issue by IMDaniyal** [taskbarter/main#14]
The backed API of Completed and the assigned task has started causing the issue. I'll look into it. But meanwhile, if you understand the issue let me know.

**Comment by mohsinht** [comment]
Yes, the problem was in $lookup.

If you want to fetch `Work` and join it up with `tasks` with `COMPLETED` State. You'll first have to fetch `Work` objects using `$match` and then in the `$lookup`, you'll have to specify which task objects you want to join.

But this has an issue, it fetches `Work` first and then joins if `Task` is complete. It will also fetch Work objects with incomplete state as empty task objects. So it is an issue, but not high alert. It will only cost a couple of bytes.

```
      {
        $match: {
          $and: [
            {
              assignedTo: mongoose.Types.ObjectId(req.user.id),
            },
          ],
        },
      },
      {
        $lookup: {
          from: 'tasks',
          let: { task_id: '$task' },
          pipeline: [
            {
              $match: {
                $expr: {
                  $and: [
                    { $eq: ['$state', TASK_COMPLETED] },
                    { $eq: ['$_id', '$$task_id'] },
                  ],
                },
              },
            },
          ],
          as: 'taskDetails',
        },
      },
```

We'll resolve this in the next update.
